services:
  app:
    build: .
    container_name: devops_app
    restart: always
    image: devops_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
  db:
    image: devops_db
    container_name: mysql_container
    restart: always # pour eviter les restart boucle inf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anime
      MYSQL_USER: julien
      MYSQL_PASSWORD: pass
    hostname: molok
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
  front:
    build: ./front
    container_name: devops_front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  db_volume: {}
